export const MODEL_VERSION = 'emissions-physics-1.0.0';
export const REGULATION_VERSION = 'conama-418-2009-consolidated-2026-08';

export const DATA_CLASSIFICATION = Object.freeze({
  NORMATIVE: 'normative',
  TECHNICAL: 'technical',
  DIDACTIC: 'didactic',
  MODEL_ASSUMPTION: 'modelAssumption',
});

export const DEFAULT_CALIBRATION = Object.freeze({
  id: 'validated-default',
  name: 'Calibração Padrão Validada',
  version: 1,
  classification: DATA_CLASSIFICATION.DIDACTIC,
  parameters: Object.freeze({
    combustionSharpness: 1,
    richCoGain: 1,
    leanO2Gain: 1,
    hcMisfireGain: 1,
    noxPeakGain: 1,
    twcLightOffC: 350,
    twcFullActivityC: 520,
    lambdaWindowWidth: 0.045,
    samplingDilutionDefault: 1,
  }),
});

export const VEHICLE_LIBRARY = Object.freeze([
  {
    vehicleId: 'SIM-OTTO-CARB-1978',
    manufacturer: 'Fabricante Didático A',
    model: 'Sedan Clássico',
    version: '1.6',
    manufactureYear: 1978,
    modelYear: 1978,
    fuel: 'gasoline',
    ethanolContent: 0,
    fuelingSystem: 'carburetor',
    lambdaSensor: false,
    closedLoop: false,
    catalyst: 'none',
    technologyGeneration: 'carbureted-no-catalyst',
    informationOrigin: 'Biblioteca fictícia do LabInspeção',
    informationClassification: DATA_CLASSIFICATION.DIDACTIC,
  },
  {
    vehicleId: 'SIM-OTTO-EFI-1998',
    manufacturer: 'Fabricante Didático B',
    model: 'Hatch Multiponto',
    version: '1.8',
    manufactureYear: 1998,
    modelYear: 1999,
    fuel: 'gasoline',
    ethanolContent: 22,
    fuelingSystem: 'multi-point-efi',
    lambdaSensor: true,
    closedLoop: true,
    catalyst: 'twc',
    technologyGeneration: 'efi-twc-closed-loop',
    informationOrigin: 'Biblioteca fictícia do LabInspeção',
    informationClassification: DATA_CLASSIFICATION.DIDACTIC,
  },
  {
    vehicleId: 'SIM-OTTO-FLEX-2008',
    manufacturer: 'Fabricante Didático C',
    model: 'Compacto Flex',
    version: '1.4',
    manufactureYear: 2008,
    modelYear: 2009,
    fuel: 'flex',
    ethanolContent: 27,
    fuelingSystem: 'multi-point-efi',
    lambdaSensor: true,
    closedLoop: true,
    catalyst: 'twc',
    technologyGeneration: 'first-generation-flex-twc',
    informationOrigin: 'Biblioteca fictícia do LabInspeção',
    informationClassification: DATA_CLASSIFICATION.DIDACTIC,
  },
  {
    vehicleId: 'SIM-OTTO-FLEX-2022',
    manufacturer: 'Fabricante Didático D',
    model: 'Hatch Flex Atual',
    version: '1.0',
    manufactureYear: 2022,
    modelYear: 2023,
    fuel: 'flex',
    ethanolContent: 27,
    fuelingSystem: 'electronic-injection',
    lambdaSensor: true,
    closedLoop: true,
    catalyst: 'twc',
    technologyGeneration: 'modern-flex-closed-loop',
    informationOrigin: 'Biblioteca fictícia do LabInspeção',
    informationClassification: DATA_CLASSIFICATION.DIDACTIC,
  },
]);
